import type { Beat } from "@/types";

export const MOCK_SPOTIFY_TRACK = [
  "https://open.spotify.com/embed/track/3VNUOCdkgs2ktqQaXg1Qjw?utm_source=generator",
  "https://open.spotify.com/embed/track/1cE2KAnTmwUCixgiKvdeqS?utm_source=generator",
  "https://open.spotify.com/embed/track/7fc2nAxRA2OLrr78Ec2mWE?utm_source=generator",
  "https://open.spotify.com/embed/track/7AsXqXjFkCaAZ8LjJpUlxl?utm_source=generator",
  "https://open.spotify.com/embed/track/39wBSKzyH3yGreBY802nMW?utm_source=generator",
  "https://open.spotify.com/embed/track/6DY0L6kKmzTyKbH12iIwmX?utm_source=generator",
];
export const MOCK_BEATS: Beat[] = [
  {
    portada: "/assets/portada-beat-1.jpg",
    name: "Chill Vibes",
    genre: "Lo-fi",
    bpm: "90",
    key: "Gm",
    price: "$20",
  },
  {
    portada: "/assets/portada-beat-1.jpg",
    name: "Trap Banger",
    genre: "Trap",
    bpm: "90",
    key: "Am",
    price: "$30",
  },
  {
    portada: "/assets/portada-beat-1.jpg",
    name: "Gritty Boom Bap",
    genre: "Boom Bap",
    bpm: "90",
    key: "Em",
    price: "$25",
  },
  {
    portada: "/assets/portada-beat-1.jpg",
    name: "Chill Vibes",
    genre: "Lo-fi",
    bpm: "90",
    key: "Gm",
    price: "$20",
  },
  {
    portada: "/assets/portada-beat-1.jpg",
    name: "Trap Banger",
    genre: "Trap",
    bpm: "90",
    key: "Am",
    price: "$30",
  },
  {
    portada: "/assets/portada-beat-1.jpg",
    name: "Gritty Boom Bap",
    genre: "Boom Bap",
    bpm: "90",
    key: "Em",
    price: "$25",
  },
  {
    portada: "/assets/portada-beat-1.jpg",
    name: "Chill Vibes",
    genre: "Lo-fi",
    bpm: "90",
    key: "Gm",
    price: "$20",
  },
  {
    portada: "/assets/portada-beat-1.jpg",
    name: "Trap Banger",
    genre: "Trap",
    bpm: "90",
    key: "Am",
    price: "$30",
  },
  {
    portada: "/assets/portada-beat-1.jpg",
    name: "Gritty Boom Bap",
    genre: "Boom Bap",
    bpm: "90",
    key: "Em",
    price: "$25",
  },
  {
    portada: "/assets/portada-beat-1.jpg",
    name: "Chill Vibes",
    genre: "Lo-fi",
    bpm: "90",
    key: "Gm",
    price: "$20",
  },
  {
    portada: "/assets/portada-beat-1.jpg",
    name: "Trap Banger",
    genre: "Trap",
    bpm: "90",
    key: "Am",
    price: "$30",
  },
  {
    portada: "/assets/portada-beat-1.jpg",
    name: "Gritty Boom Bap",
    genre: "Boom Bap",
    bpm: "90",
    key: "Em",
    price: "$25",
  },
  {
    portada: "/assets/portada-beat-1.jpg",
    name: "Chill Vibes",
    genre: "Lo-fi",
    bpm: "90",
    key: "Gm",
    price: "$20",
  },
  {
    portada: "/assets/portada-beat-1.jpg",
    name: "Trap Banger",
    genre: "Trap",
    bpm: "90",
    key: "Am",
    price: "$30",
  },
  {
    portada: "/assets/portada-beat-1.jpg",
    name: "Gritty Boom Bap",
    genre: "Boom Bap",
    bpm: "90",
    key: "Em",
    price: "$25",
  },
  {
    portada: "/assets/portada-beat-1.jpg",
    name: "Chill Vibes",
    genre: "Lo-fi",
    bpm: "90",
    key: "Gm",
    price: "$20",
  },
  {
    portada: "/assets/portada-beat-1.jpg",
    name: "Trap Banger",
    genre: "Trap",
    bpm: "90",
    key: "Am",
    price: "$30",
  },
  {
    portada: "/assets/portada-beat-1.jpg",
    name: "Gritty Boom Bap",
    genre: "Boom Bap",
    bpm: "90",
    key: "Em",
    price: "$25",
  },
  {
    portada: "/assets/portada-beat-1.jpg",
    name: "Chill Vibes",
    genre: "Lo-fi",
    bpm: "90",
    key: "Gm",
    price: "$20",
  },
  {
    portada: "/assets/portada-beat-1.jpg",
    name: "Trap Banger",
    genre: "Trap",
    bpm: "90",
    key: "Am",
    price: "$30",
  },
  {
    portada: "/assets/portada-beat-1.jpg",
    name: "Gritty Boom Bap",
    genre: "Boom Bap",
    bpm: "90",
    key: "Em",
    price: "$25",
  },
];
export const MOCK_SOCIAL_MEDIA = [
  {
    page: "instagram",
    link: "instagram",
    className: "bg-gradient-to-bl from-purple-600 via-pink-500 to-yellow-400",
  },
  { page: "youtube", link: "youtube", className: "bg-white" },
  {
    page: "github",
    link: "github",
    className: "bg-gray-800",
  },
  {
    page: "x",
    link: "x",
    className: "bg-black",
  },
];
export const MOCK_YOUTUBE_VIDEOS = [
  "https://www.youtube.com/embed/PrJ44s1KDRc?si=U3nfhr3isj_DpX2W",
  "https://www.youtube.com/embed/F2ZgxyBY8HQ?si=U_HI9SZBD-n5X2t8",
];
